fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
#    registration:
#        form:
#        type: App\Form\Type\RegistrationFormType
    from_email:
        address: bookwoorm@yandex.ru
        sender_name: BOOKWOORM
    service:
        mailer: fos_user.mailer.twig_swift