language: php
sudo: false

php:
  - 7.4

#services:
#  - mysql

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.symfony
    - ./bin/.phpunit

before_install:
  - composer self-update
  - wget https://get.symfony.com/cli/installer -O - | bash
  - yarn install && yarn encore dev

install:
  - composer install
  - ./bin/phpunit install
  #- ./bin/console doctrine:database:create

script:
  - $HOME/.symfony/bin/symfony security:check
  - composer validate --no-check-all --strict
  - ./bin/console lint:yaml config --parse-tags
  - ./bin/console lint:twig templates --show-deprecations
  - ./bin/console lint:container
  #- ./bin/console doctrine:migrations:migrate --no-interaction
  #- ./bin/console doctrine:migrations:migrate first --no-interaction
  #- ./bin/console doctrine:migrations:migrate --no-interaction
  - ./bin/console doctrine:schema:validate --skip-sync --no-interaction
  - ./bin/phpunit

deploy:
  provider: heroku
  app: "bookwoorm"
  api_key:
    secure: "7dcf578c-062a-4585-b613-104897f5c5df"

notifications:
  email: paboriskin@gmail.com
