language: php
sudo: false

#services:
#  - mysql

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit
env:
  - SYMFONY_VERSION="4.4.*" DB=mysql

matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - composer config extra.symfony.require $SYMFONY
  - yarn install && yarn encore dev

install:
  - composer install
  - ./bin/phpunit install
  #- ./bin/console doctrine:database:create

script:
  - ./bin/phpunit
  - composer validate --no-check-all --strict
  - symfony security:check
  - ./bin/console lint:yaml config --parse-tags
  - ./bin/console lint:twig templates --env=prod
  - ./bin/console lint:container
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - composer validate

notifications:
  email: paboriskin@gmail.com
