language: php
sudo: false

php:
  - 7.4

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.symfony
    - ./bin/.phpunit

before_install:
  - composer self-update
  - wget https://get.symfony.com/cli/installer -O - | bash

install:
  - composer install
  - yarn install && yarn encore dev
  - ./bin/phpunit install

script:
  - $HOME/.symfony/bin/symfony security:check
  - composer validate --no-check-all --strict
  - ./bin/console lint:yaml config --parse-tags
  - ./bin/console lint:twig templates --show-deprecations
  - ./bin/console lint:container
  - ./bin/console doctrine:database:create --env=test
  - ./bin/console doctrine:migrations:migrate --no-interaction --env=test
  - ./bin/console doctrine:migrations:migrate first --no-interaction --env=test
  - ./bin/console doctrine:migrations:migrate --no-interaction --env=test
  - ./bin/console doctrine:schema:validate --skip-sync --no-interaction --env=test
  - ./bin/phpunit

deploy:
  provider: heroku
  app: "bookwoorm"
  api_key: "$HEROKU_API_KEY"
  edge: true # opt in to dpl v2
  cleanup: true
  - composer dump-env prod
  - yarn encore production --progress

notifications:
  email: paboriskin@gmail.com
