version: "3.7"
services:

    mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_DB_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DB_NAME}"
        MYSQL_USER: "${MYSQL_DB_USERNAME}"
        MYSQL_PASSWORD: "${MYSQL_DB_PASSWORD}"
      ports:
        - "3306:3306"

    nginx:
      image: nginx:alpine
      container_name: nginx
      volumes:
        - ./:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./var/log/nginx:/var/log/nginx
      ports:
        - "80:80"
      depends_on:
       - php-fpm
       - mysql
       - encore

    php-fpm:
      build: docker/php-fpm
      container_name: app
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      ports:
        - "9000:9000"

    encore:
      image: node:13-alpine
      container_name: encore
      working_dir: /app
      volumes:
        - ./:/app
      ports:
        - "8080:8080"
      command: ["yarn", "dev-server", "--host=0.0.0.0"]
