version: "3.7"
services:

    mysql:
      image: mysql:5.7
      container_name: bw-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=pass_root
        - MYSQL_DATABASE=db_name
        - MYSQL_USER=db_user
        - MYSQL_PASSWORD=pass_user
      ports:
        - "3306:3306"

    nginx:
      image: nginx:alpine
      container_name: bw-nginx
      volumes:
          - ./:/var/www
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./var/log/nginx:/var/log/nginx
      ports:
       - "80:80"
      depends_on:
       - php-fpm
       - mysql

    php-fpm:
      build: docker/php-fpm
      container_name: bw-php-fpm
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      ports:
        - "9000:9000"
