version: "3.7"
services:

    mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_DB_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DB_NAME}"
        MYSQL_USER: "${MYSQL_DB_USERNAME}"
        MYSQL_PASSWORD: "${MYSQL_DB_PASSWORD}"
      ports:
        - "${MYSQL_DB_PORT}:3306"
      networks:
        - internal

    nginx:
      image: nginx:alpine
      container_name: nginx
      volumes:
        - ./:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./var/log/nginx:/var/log/nginx
      ports:
        - "80:80"
      depends_on:
       - app
       - encore
      networks:
        - internal

    app:
      build: docker/php-fpm
      container_name: app
      working_dir: /app
      volumes:
        - ./:/app:cached
        - ./var/cache/:/app/var/cache:delegated
        - ./vendor/:/app/vendor:delegated
      ports:
        - "9000:9000"
      environment:
        PHP_IDE_CONFIG: "serverName=docker"
      depends_on:
        - mysql
      networks:
        - internal
      restart: always

    encore:
      image: node:13-alpine
      container_name: encore
      working_dir: /app
      volumes:
        - ./:/app:cached
      ports:
        - "8080:8080"
      networks:
        - internal
      command: ["yarn", "dev-server", "--host=0.0.0.0"]

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28